export const GET_USERS = 'GET_USERS';
export const DELETE_USER = 'DELETE_USER';
export const LOGIN_USER = 'LOGIN_USER'
export const ADD_USER = 'ADD_USER';
export const GET_ERRORS = 'GET_ERRORS';

//Auth
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER = 'REGISTER';
export const AUTH_ERROR_HANDLE = 'AUTH_ERROR_HANDLE';

//Homestay
export const LOAD_LIST_HOMESTAY = 'LOAD_LIST_HOMESTAY'
export const LOAD_LIST_HOMESTAY_FAIL = 'LOAD_LIST_HOMESTAY_FAIL'
export const LOAD_DETAIL_HOMESTAY = 'LOAD_DETAIL_HOMESTAY'
export const LOAD_DETAIL_HOMESTAY_FAIL = 'LOAD_DETAIL_HOMESTAY_FAIL'

//Facility
export const LOAD_LIST_FACILITY = 'LOAD_LIST_FACILITY'
export const LOAD_LIST_FACILITY_FAIL = 'LOAD_LIST_FACILITY_FAIL'
export const CHECKED_FACILITIES = 'CHECKED_FACILITIES'

//Upload
export const UPLOAD_BASIC_INFO = 'UPLOAD_BASIC_INFO'
export const UPLOAD_ADDRESS_INFO = 'UPLOAD_ADDRESS_INFO'
export const UPLOAD_DESCRIPTION = 'UPLOAD_DESCRIPTION'
export const UPLOAD_FACILITIES = 'UPLOAD_FACILITIES'
export const UPLOAD_PRICES = 'UPLOAD_PRICES'
export const UPLOAD_RESESRVATION_DATE = 'UPLOAD_RESESRVATION_DATE'
export const UPLOAD_IMAGES = 'UPLOAD_IMAGES'

//Booking
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS'
export const BOOKING_FAIL = 'BOOKING_FAIL'


